- set_fact:
      ao_har: "{{ ao_har | default({}) | combine({'enabled': http_application_routing}) }}"
  when: http_application_routing is defined

- set_fact:
      ao_m: "{{ ao_m | default({}) | combine({'enabled': monitoring, 'log_analytics_workspace_resource_id': workspace_resource_id}) }}"
  when: monitoring is defined

- set_fact:
    "{{ item.key }}": "{{ {} | combine({ 'enabled': item.value }) }}"
  with_items:
    - {'key': 'ao_har', 'value': "{{ http_application_routing }}" }
    - {'key': 'ao_m', 'value': "{{ monitoring }}" }
    - {'key': 'ao_vn', 'value': "{{ virtual_node }}" }
  when: item.value is defined

- set_fact:
    ao_m: "{{ ao_m | combine({'log_analytics_workspace_resource_id': workspace_resource_id}) }}"
  when: monitoring and workspace_resource_id

- set_fact:
    ao_vn: "{{ ao_vn | combine({'subnet_resource_id': virtual_node_subnet_id}) }}"
  when: virtual_node and virtual_node_subnet_id

- set_fact:
    addon: "{{ addon | default({}) | combine({item.key: item.value}) }}"
  with_items:
    - {'key': 'http_application_routing', 'value': ao_har}
    - {'key': 'monitoring', 'value': ao_m}
    - {'key': 'virtual_node', 'value': ao_vn}