---
# tasks file for aks
- include_tasks: resource_group.yml

- include_tasks: aks_facts.yml

- include_tasks: parameter.yml

- include_tasks: addon.yml

- include_tasks: k8s_version.yml
  when: kubernetes_version not defined and kubernetes_version_bak not defined

- name: Create or update AKS state
  azure_rm_aks:
      name: "{{ name }}"
      resource_group: "{{ resource_group }}"
      location: "{{ location }}"
      dns_prefix: "{{ dns_prefix }}"
      kubernetes_version: "{{ kubernetes_version }}"
      enable_rbac: "{{ enable_rbac }}"
      service_principal:
          clinet_id: "{{ service_principal }}"
          client_secret: "{{ client_secret }}"
      linux_profile:
          admin_user: "{{ admin_username }}"
          ssh_key: "{{ ssh_key }}"
      agent_pool_profiles:
        - name: "{{ nodepool_name }}"
          count: "{{ node_count }}"
          vm_size: "{{ node_vm_size }}"
          os_disk_size_gb: "{{ node_osdisk_size_gb }}"
          storage_profile: "{{ storage_profile }}"
          vnet_subnet_id: "{{ vnet_subnet_id }}"
          max_pods: "{{ max_pods }}"
          os_type: "{{ os_type }}"
      network_profile:
          network_plugin: "{{ network_plugin }}"
          network_policy: "{{ network_policy }}"
          pod_cidr: "{{ pod_cidr }}"
          service_cidr: "{{ service_cidr }}"
          dns_service_ip: "{{ dns_service_ip }}"
          docker_bridge_cidr: "{{ docker_bridge_cidr }}"
      aad_profile:
          client_app_id: "{{ aad_client_app_id }}"
          server_app_id: "{{ aad_server_app_id }}"
          server_app_secret: "{{ aad_server_app_secret }}"
          tenant_id: "{{ aad_tenant_id }}"
      addon: "{{ addon }}"