- set_fact:
      location: "{{ location | default(location_bak, true) }}"
      enable_rbac: "{{ enable_rbac | default(enable_rbac_bak, true) }}"
      node_count: "{{ node_count | default(node_count_bak, true) }}"
      max_pods: "{{ max_pods | default(max_pods_bak, true) }}"
      nodepool_name: "{{ nodepool_name | default(nodepool_name_bak, true) }}"
      node_osdisk_size_gb: "{{ node_osdisk_size_gb | default(node_osdisk_size_gb_bak, true) }}"
      node_vm_size: "{{ node_vm_size | default(node_vm_size_bak, true) }}"

- set_fact:
      dns_prefix: "{{ dns_prefix | default(name, true) }}"

- set_fact:
      ssh_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  when: ssh_key not defined
